// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
